In [1]:
import pandas as pd
data = pd.read_csv("lab3_gwas.assoc.linear", delim_whitespace=True)
data

        CHR         SNP         BP A1 TEST  NMISS     BETA    STAT         P
0        10  rs11252127      98087  T  ADD    207 -0.20430 -1.6060  0.109700
1        10   rs7909677     111955  G  ADD    207  0.19160  0.9108  0.363500
2        10  rs11591988     126070  T  ADD    207 -0.14700 -0.6690  0.504300
3        10  rs12768206     134767  A  ADD    207 -0.05717 -0.6032  0.547100
4        10  rs10904561     135656  G  ADD    207 -0.17850 -1.4710  0.142900
...     ...         ...        ... ..  ...    ...      ...     ...       ...
835556    9   rs9777369  141018423  T  ADD    207  0.50510  3.3960  0.000822
835557    9  rs11137376  141025328  A  ADD    207  0.36110  2.1310  0.034320
835558    9  rs17583562  141026318  A  ADD    207 -0.71220 -3.3240  0.001052
835559    9  rs11137379  141027939  A  ADD    207 -0.13960 -0.9986  0.319200
835560    9   rs9314655  141066491  A  ADD    207  0.31500  4.1770  0.000044

[835561 rows x 9 columns]

In [2]:
result=pd.read_csv('lab3.csv')
result

        CHR         BP         SNP REF A1      BETA         P
0        10      98087  rs11252127   C  T -0.204280  0.109734
1        10     111955   rs7909677   A  G  0.191564  0.363471
2        10     126070  rs11591988   C  T -0.146990  0.504264
3        10     134767  rs12768206   A  G  0.057168  0.547052
4        10     135656  rs10904561   T  G -0.178488  0.142948
...     ...        ...         ...  .. ..       ...       ...
835556    9  141018423   rs9777369   C  T  0.505054  0.000822
835557    9  141025328  rs11137376   C  A  0.361115  0.034320
835558    9  141026318  rs17583562   G  A -0.712181  0.001052
835559    9  141027939  rs11137379   G  A -0.139623  0.319168
835560    9  141066491   rs9314655   G  A  0.314990  0.000044

[835561 rows x 7 columns]

In [3]:
# grab all snps in to snp-result.txt
snps = data['SNP']
with open('snp-result.txt', 'w') as result_snp:
    for snp in snps:
        result_snp.write(snp + '\n')
result_snp.close()

In [4]:
snp2 = result['SNP']

with open('our-snp.txt', 'w') as result_snp2:
    for snp in snp2:
        result_snp2.write(snp + '\n')
result_snp2.close()

In [5]:
! diff snp-result.txt our-snp.txt

In [6]:
p_vals = data['P']
our_pvals = result['P']
result_p = []
for i in range(len(p_vals)):
    if (abs(our_pvals[i] - p_vals[i]) < 0.01):
        result_p.append(True)
    else:
        print('FALSE')
print(len(result_p) == len(p_vals))

True

In [7]:
beta_valus = data['BETA']
our_beta = result['BETA']
result_beta = []
for i in range(len(beta_valus)):
    if (abs(abs(our_beta[i]) - abs(beta_valus[i])) < 0.01):
        result_beta.append(True)
    else:
        print('FALSE')

print(len(result_beta) == len(beta_valus))

True

In [8]:
a = '0|0	0|0	0|0	2|0	2|0	0|0	0|0	0|0	0|0	1|0	2|0	2|2	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|2	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	2|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	2|0	0|0	0|0	0|0	2|1	0|0	0|0	0|2	0|0	0|0	0|2	0|2	0|0	0|2	0|0	0|0	0|2	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	2|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	2|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	2|2	2|0	0|0	0|2	0|2	0|0	0|0	0|0	0|0	0|0	2|0	0|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|2	0|0	0|0	0|0	0|0	0|2	0|0	0|0	0|0	0|0	0|2	0|0	0|0	0|0	2|0	0|0	2|0	1|0	0|0	0|0	0|2	0|0	2|2	1|0	0|0	0|0	0|0	0|2	0|2	0|0	0|0	2|2	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|2	0|0	0|0	0|0	0|0	0|0	0|0	0|0	2|0	2|0	2|0	0|0	0|0	2|0	0|0	0|0	0|0	2|2	0|0	0|0'
genotype_inputs = a.split('\t')
genotype_inputs

['0|0',
 '0|0',
 '0|0',
 '2|0',
 '2|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '1|0',
 '2|0',
 '2|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '0|0',
 '0|0',
 '0|0',
 '2|1',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|2',
 '0|2',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|2',
 '2|0',
 '0|0',
 '0|2',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '0|1',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '0|0',
 '2|0',
 '1|0',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '2|2',
 '1|0',
 '0|0',
 '0|0',
 '0|0',
 '0|2',
 '0|2',
 '0|0',
 '0|0',
 '2|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|2',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '0|0',
 '2|0',
 '2|0',
 '2|0',
 '0|0',
 '0|0',
 '2|0',
 '0|0',
 '0|0',
 '0|0',
 '2|2',
 '0|0',
 '0|0']

In [9]:
def assign_multi_genoType(ref, alt, queries):
    genotypes = []
    # create dictionary based on input alt
    alt = alt.split(',')
    genotype = ''
    dictionary = {
        "0" : ref
    }
    
    alt_allele_counts = []
    # if there is multi alt allele, map them to dictionary one by one 
    index = 1
    for alternative in alt:
        dictionary[str(index)] = alternative
        index+=1
        alt_allele_counts.append(0)
    # fill in genotypes list based on query 
    for query in queries: 
        genotype = ''
        if '|' in query:
            query = query.split('|')
        elif '/' in query:
            query = query.split('/')
        for num in query:
            if num in dictionary.keys():
                # if it is a alternaitve allele
                if (int(num) > 0):
                    # update its count in gt_allele_counts
                    alt_allele_counts[int(num)-1] += 1
                genotype += dictionary[num]
        genotypes.append(genotype)
    
    # if more than one alt allele exists
    sig_alt_allele = ''
    if (len(alt_allele_counts) > 1):
        # find the significant allele
        sig_alt_allele = alt_allele_counts.index(max(alt_allele_counts)) + 1
        sig_alt_allele = dictionary[str(sig_alt_allele)]
        #print('most significant alternative allele is: {}'.format(sig_alt_allele))
        # reassign dictionary to only contains most significant alt allele 
        minor_allele = list(dictionary.values())
        minor_allele.remove(ref)
        minor_allele.remove(sig_alt_allele)

        dictionary = [ref, sig_alt_allele]
        print(dictionary)
        # check genotype with other insignificant alt allele by
        # checking if it has invalid length
        maxLen = max(len(ref), len(sig_alt_allele))
        maxLen *= 2
        minLen = min(len(ref), len(sig_alt_allele))
        minLen *= 2
        # or checking it has allele nonexistent in updated dictionary 
        for i in range(len(genotypes)):
            geno = genotypes[i]
            # check for invalid length genos
            if len(geno) > maxLen or len(geno) < minLen:
                #print(geno)
                genotypes[i] = 'N'
                continue
            # check for invalid allele 
            if destructGeno(geno, dictionary, minor_allele):
                print(geno)
                genotypes[i] = 'N' 
                continue 
          
    return genotypes, sig_alt_allele

In [10]:
def destructGeno(geno, allowed_alle, minor_alleles):
    for i in range(2):
        # find allowed allele in geno
        ref_pos = geno.find(allowed_alle[0])
        alt_pos = geno.find(allowed_alle[1])
    
        # if none of allowed geno found, return deleted = TRUE
        comp_len = 0                     
        if (ref_pos != 0 and alt_pos != 0):
            return True
        # if both refers to first position, use the longer one 
        elif(ref_pos == 0 and alt_pos == 0):
            comp_len = max(len(allowed_alle[0]), len(allowed_alle[1]))
            # but if using larger length make it = 0
            if ((i == 0 and geno[comp_len:] == '')):
                comp_len = min(len(allowed_alle[0]), len(allowed_alle[1]))
        # otherwise, record its length to compare with potential minor allele 
        elif(ref_pos == 0):
            comp_len = len(allowed_alle[0])
        else:
            comp_len = len(allowed_alle[1])
    
        # store minor alleles position
        minor_pos = []
        for minor in minor_alleles:
            minor_pos.append(geno.find(minor))
           
        minor_alt = ''
        for j in range(len(minor_pos)):
            # once we recognize other minor allele existence
            if (minor_pos[j] == 0):
                minor_alt = minor_alleles[j]
   
        # if there is a minor allele start at pos 0, and length higher than ref/alt alllele start at pos 0
        # geno contains minor allele that needs to be removed
        if len(minor_alt) > comp_len:
            # when checking for first allele, make sure using minor alt does not use up all nucleotide
            if ((i == 0 and geno[len(minor_alt):] != '')):
                return True
            
            # when it's second allele, it is definitely the minor alt so return 1
            if (i == 1 and geno[len(minor_alt):] == ''):
                return True 
        # update geno
        geno = geno[comp_len:]
    return False

In [11]:
genotypes, sig_alt_allele = assign_multi_genoType('TGCACGCTGG', 'TGCACGCTGGGCACGCTGG,T', genotype_inputs)
print(sig_alt_allele)
print(genotypes)

['TGCACGCTGG', 'T']
TTGCACGCTGGGCACGCTGG
T
['TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'N', 'TTGCACGCTGG', 'TT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'N', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TT', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'N', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'N', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TT', 'N', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG', 'TT', 'TGCACGCTGGTGCACGCTGG', 'TGCACGCTGGTGCACGCTGG']

In [12]:
destructGeno('TTGCACGCTGGGCACGCTGG',['TGCACGCTGG', 'T'], ['TGCACGCTGGGCACGCTGG'])

True

In [13]:
# this function will compute maf based on ref allele, alt allele, and genotypes
# genotypes = list of genotypes ['AA', 'TT']
def calculate_maf(ref_allele, alt_allele, genotypes):
    # calculate maf
    maf = -1
    ref_allele_freq = 0
    alt_allele_freq = 0
    total = 0
    ref_l = len(ref_allele)
    alt_l = len(alt_allele)
    for genotype in genotypes:
        # skip empty genotypes 
        if (genotype == 'N'):
            continue
        # update total # of alleles by 2
        total += 2
        for i in range(2): 
            # find index of allele position, check first allele position 
            ref_index = genotype.find(ref_allele)
            alt_index = genotype.find(alt_allele)
            if (ref_index == 0 and alt_index == 0):
                if (ref_l > alt_l):
                    ref_allele_freq += 1
                    genotype = genotype[ref_l:]
                else:
                    alt_allele_freq+=1
                    genotype = genotype[alt_l:]
            elif(ref_index == 0):
            # if first allele is ref allele, split it using ref_l 
                ref_allele_freq += 1
                genotype = genotype[ref_l:]
            # otherwise, split it using alt_l
            else:
                alt_allele_freq+=1
                genotype = genotype[alt_l:]

    # if genotype all N, return 0
    if (total == 0):
        return 0
    # find minor allele via proportion 
    maf = min(ref_allele_freq/total, alt_allele_freq/total)
    return maf

In [14]:
calculate_maf('G', 'T', genotypes)

0.4504950495049505